
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
     <head>
      <script src="https://dev-www.sunbeltrentals.com/etc.clientlibs/sunbeltrentals/clientlibs/clientlib-cc.lc-798974caf87cf2380d0a55bd20599ae3-lc.min.js"></script>
      <link
          rel="stylesheet"
          href="https://qa-www3.sunbeltrentals.com/etc.clientlibs/sunbeltrentals/clientlibs/clientlib-cc.lc-7e8b97c136dc34aeacf28980a54cb17d-lc.min.css"
          integrity="sha384-..." // Optional: For security, you can use the `integrity` and `crossorigin` attributes
        />
     </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
