
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <head>
	  <meta name="urn:adobe:aue:system:aem" content="aem:https://localhost:8443" />
	  <meta name="urn:adobe:aue:system:aemconnection" content="aem:https://localhost:8443" />
	  <meta name="urn:adobe:aue:config:service" content="https://localhost:8000" />
      <script src="https://universal-editor-service.adobe.io/cors.js" async></script>
      <script src="https://localhost:3000/clientlib-cc.min.js"></script>
	  <link rel="preload" href="/sunbelticons.ttf" as="font" type="font/ttf" />
      <link
          rel="stylesheet"
		  href="https://localhost:3000/clientlib-cc.min.css"
          //href="https://dev-www.sunbeltrentals.com/etc.clientlibs/sunbeltrentals/clientlibs/clientlib-cc.min.css"
          integrity="sha384-..." // Optional: For security, you can use the `integrity` and `crossorigin` attributes
        />
     </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
